#!/usr/bin/exec-suid -- /usr/bin/python3.12 -I
import sys
import os
import re

sys.path.append('/challenge')
from pacePythonTester import ExecutionAgent as ex

def print_flag():
    try:
        with open("/flag", "r") as f:
            print("Good comparisons! Here's the flag:")
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

def run_and_check_script(user_script_path):

    for a,b in [(1,2),(2,1),(1,1)]:
        answer = str(a <= b)

        # Run their program with the test case
        try:
            stdout, stderr = ex.run(user_script_path, input=f"{a}\n{b}\n")
        except TypeError as e:
            """ Issue with noneType return """
            print("Error:", e)
            exit()

        if not stdout.strip().endswith(answer):
            print(f"Error: Make sure that you print True if the first number is less than or equal to the second number")
            exit()

    print_flag()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("You forgot to give me your python file!")
        print("Try running: '/challenge/verify yourFile.py'")
        sys.exit(1)

    user_script_path = sys.argv[1]
    run_and_check_script(user_script_path)
